language: node_js
node_js:
  - '0.12'
  - 'iojs'
before_install:
  - npm install jscs jshint
script:
  - npm test
  - ./node_modules/.bin/jshint -c .jshintrc index.js test/app.js
  - ./node_modules/.bin/jscs -c .jscsrc index.js test/app.js
after_success:
  - npm run cover
